schema_version = "1.0.0"
id = "sprite_sheet_maker"
version = "1.5.0"
name = "Sprite Sheet Maker"
tagline = "3D to 2D sprite sheet converter with optional pixelation"
maintainer = "Manas R. Makde"
type = "add-on"
website = "https://github.com/ManasMakde/SpriteSheetMaker/"
tags = ["Animation", "Render"]
blender_version_min = "5.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
platforms = ["windows-x64", "windows-arm64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = [
  "./wheels/pillow-12.0.0-cp311-cp311-macosx_10_10_x86_64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-win_arm64.whl",
]